### ISSUE TITLE
Initial request not returning

### ISSUE THREAD

**Issue by RothcoLtd** [teference/shopify-dotnet#2]
Hello

I am writing an app to get data from Shopify and I am using the shopify-dotnet code as specified EXCEPT I am changing it all to VB.net (my language).

The initial call works fine in my test environment but the return is not working it gets as far as 

https://3dbac9412ca6.ngrok.io/shop50/install?hmac=40bb07513629529814a7ccff0cce7cac66a49d2d0f711bdb8da18832d03e1501&shop=rothcoltd.myshopify.com&timestamp=1604320792

and does not call the Authorisation routine 

According to the shopify documentation I believe that there should be a nonce in there somewhere?

**Comment by jsinh** [comment]
Hello @RothcoLtd 

I haven't really worked on this NuGet package since 2015 - almost 5 years. Only in 2018 - I did a TLS patch that was from a PR that a kind gentleman submitted which I merged and created a new package for it.

I am not actively maintaining this project anymore - so if you have some reference links I can refer to or more details of what part of the code needs changes to adhere to the broken OAuth I can try to spend some time over the weekend to help you fix it.

By just quick look at this scope list: https://github.com/teference/shopify-dotnet/blob/master/source/Shopify.OAuth%20(NET2.0)/OAuthScope.cs
I am not even sure if that is relevant till now? 

and while I am still not sure where is the official document that explains the latest OAuth flow that Shopify supports, I believe you need a `Nonce` field in this https://github.com/teference/shopify-dotnet/blob/master/source/Shopify.OAuth%20(NET2.0)/OAuthState.cs class logically speaking.

If you know exactly what needs to be fixed, PR would be appreciated, I can get a package pushed on merged, thanks!

**Comment by RothcoLtd** [comment]
Hi

 

Many thanks for coming back so quickly

 

I have a suspicion that the part that is missing is the nonce – as defined here

 

https://shopify.dev/tutorials/authenticate-with-oauth

 

…under “Ask for permission”

 

 

I am getting an error in the OAuthState of HMAC validation failed

 

Kind regards

 

Roy Thompson

Director

Rothco Ltd

Company Registration No. 3125668

Registered in England

VAT Number GB 750 9986 83

 

Registered Address:-

1 London Road

Ipswich

Suffolk

IP4 2HA

U.K.

 

 

P Before printing, please think about the environment

This email, together with any attachments, is for the exclusive and confidential use of the addressee(s) and may contain legally privileged information. Any other distribution, use or reproduction without the sender's prior consent is unauthorised and strictly prohibited. If you have received this message in error, please notify the sender by email immediately and delete the message from your computer without making any copies

**Comment by jsinh** [comment]
@RothcoLtd Thanks for the reference link. I can help make that change. But don’t have a clear way to test it until I setup everything. I can create temp local copy of the change DLL which you can try out and confirm the fix after which I can push new NuGet for it. Please reach out on skype to collab when you can: jachauhan

**Comment by RothcoLtd** [comment]
Hi Jaspalsinh

 

There is no rush on this as I am going to be busy on other issues for the next week or so.

 

Let me know when you have made the changes and I will try it

 

Kind regards

 

Roy

 

Roy Thompson

Director

Rothco Ltd

Company Registration No. 3125668

Registered in England

VAT Number GB 750 9986 83

 

Registered Address:-

1 London Road

Ipswich

Suffolk

IP4 2HA

U.K.

 

 

P Before printing, please think about the environment

This email, together with any attachments, is for the exclusive and confidential use of the addressee(s) and may contain legally privileged information. Any other distribution, use or reproduction without the sender's prior consent is unauthorised and strictly prohibited. If you have received this message in error, please notify the sender by email immediately and delete the message from your computer without making any copies
